# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-14 08:48
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import form_document.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0009_auto_20160904_1015'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedFormDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(default='Untitled Form', max_length=256)),
                ('uploaded_document', models.FileField(help_text='The document uploaded used for populating after a form is completed', max_length=255, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=form_document.models.document_path)),
                ('form_data', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('document_mapping', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('form_config', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormDocumentAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field='cached_image_height', storage=django.core.files.storage.FileSystemStorage(), upload_to=form_document.models.original_document_path, width_field='cached_image_width')),
                ('order', models.SmallIntegerField(default=0)),
                ('cached_image_width', models.IntegerField(null=True)),
                ('cached_image_height', models.IntegerField(null=True)),
                ('form_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_assets', to='form_document.FixedFormDocument')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FormDocumentCompanyShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('company_visible', models.BooleanField(default=False, help_text='If company visible is not true, only the compnay admin can view the document')),
            ],
            options={
                'verbose_name': 'FormCompanyShare',
                'verbose_name_plural': 'FormCompanyShares',
            },
        ),
        migrations.CreateModel(
            name='FormDocumentLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('access_code', models.CharField(max_length=12)),
                ('sending_method', models.IntegerField(choices=[(0, 'Direct'), (1, 'Email'), (2, 'SMS')], default=0)),
                ('hash', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormDocumentResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('last_interactive_timestamp', models.DateTimeField(auto_now=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('answers', django.contrib.postgres.fields.jsonb.JSONField()),
                ('status', models.SmallIntegerField(choices=[(1, 'Unopen'), (5, 'Abandoned'), (2, 'Opened'), (3, 'Saved'), (4, 'Submitted'), (6, 'Auto Saved')], default=1)),
            ],
            options={
                'verbose_name': 'FormResponse',
                'verbose_name_plural': 'FormResponses',
            },
        ),
        migrations.CreateModel(
            name='FormDocumentResponseCompanyPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('from_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.Company')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_document.FormDocumentResponse')),
                ('to_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.Company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormDocumentResponseUserPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms_responses_shared_to_other_users', to=settings.AUTH_USER_MODEL)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_document.FormDocumentResponse')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_responses_received_from_other_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormDocumentTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(default='Untitled Form', max_length=256)),
                ('slug', models.SlugField(blank=True, help_text='Use for short URL sharing')),
                ('uploaded_document', models.FileField(help_text='The document uploaded used for populating after a form is completed', max_length=255, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=form_document.models.document_path)),
                ('form_data', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('document_mapping', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('form_config', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('access_code', models.CharField(max_length=4, null=True)),
                ('cached_sha1', models.CharField(blank=True, max_length=40)),
                ('owner', models.ForeignKey(help_text='The owner of this document', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FormTemplate',
                'verbose_name_plural': 'FormTemplates',
            },
        ),
        migrations.CreateModel(
            name='FormDocumentUserShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('form_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms_shared_to_other_users', to='form_document.FormDocumentTemplate')),
                ('from_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms_received_from_other_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FormUserShare',
                'verbose_name_plural': 'FormUserShares',
            },
        ),
        migrations.AddField(
            model_name='formdocumentresponse',
            name='form_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_document.FormDocumentTemplate'),
        ),
        migrations.AddField(
            model_name='formdocumentresponse',
            name='receiver_user',
            field=models.ForeignKey(help_text='The user who submitted the form, optional', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_form_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formdocumentresponse',
            name='sender_user',
            field=models.ForeignKey(help_text='The user who submitted the form, optional', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_forms_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formdocumentlink',
            name='form_response',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='form_document.FormDocumentResponse'),
        ),
        migrations.AddField(
            model_name='formdocumentlink',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formdocumentcompanyshare',
            name='form_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_document.FormDocumentTemplate'),
        ),
        migrations.AddField(
            model_name='formdocumentcompanyshare',
            name='from_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms_shared_to_other_companies', to='accounts.Company'),
        ),
        migrations.AddField(
            model_name='formdocumentcompanyshare',
            name='to_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms_received_from_other_companies', to='accounts.Company'),
        ),
        migrations.AddField(
            model_name='fixedformdocument',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_document.FormDocumentTemplate'),
        ),
        migrations.AlterUniqueTogether(
            name='formdocumentusershare',
            unique_together=set([('form_template', 'to_user')]),
        ),
        migrations.AlterUniqueTogether(
            name='formdocumentcompanyshare',
            unique_together=set([('form_template', 'to_company')]),
        ),
    ]
