# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-11 07:33
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import form_document.models
import storages.backends.gs


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_auto_20160528_0119'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(default='Untitled Form', max_length=256)),
                ('slug', models.SlugField(help_text='Use for short URL sharing', null=True)),
                ('uploaded_document', models.FileField(help_text='The document uploaded used for populating after a form is completed', null=True, storage=storages.backends.gs.GSBotoStorage(acl='private', bucket='emondo-documents', querystring_auth=True, querystring_expire=600), upload_to=form_document.models.document_path)),
                ('processed_documents', django.contrib.postgres.fields.ArrayField(base_field=models.FileField(storage=storages.backends.gs.GSBotoStorage(acl='private', bucket='emondo-documents', querystring_auth=True, querystring_expire=600), upload_to=form_document.models.document_path), help_text='List of images that can be viewed in browser', null=True, size=None)),
                ('form_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('owner', models.ForeignKey(help_text='The owner of this document', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'verbose_name': 'Form',
                'verbose_name_plural': 'Forms',
            },
        ),
        migrations.CreateModel(
            name='FormDocumentCompanyShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('company_visible', models.BooleanField(default=False, help_text='If company visible is not true, only the compnay admin can view the document')),
                ('form_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_document.FormDocument')),
                ('from_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms_shared_to_other_companies', to='accounts.Company')),
                ('to_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms_received_from_other_companies', to='accounts.Company')),
            ],
            options={
                'verbose_name': 'FormCompanyShare',
                'verbose_name_plural': 'FormCompanyShares',
            },
        ),
        migrations.CreateModel(
            name='FormDocumentLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('access_code', models.CharField(max_length=12, null=True)),
                ('hash', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormDocumentResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('last_interactive_timestamp', models.DateTimeField(auto_now=True)),
                ('form_response_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('status', models.SmallIntegerField(choices=[(1, 'Unopen'), (5, 'Abandoned'), (2, 'Opened'), (3, 'Saved'), (4, 'Submitted')], default=1)),
                ('form_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_document.FormDocument')),
                ('receiver_user', models.ForeignKey(help_text='The user who submitted the form, optional', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_form_responses', to=settings.AUTH_USER_MODEL)),
                ('sender_user', models.ForeignKey(help_text='The user who submitted the form, optional', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_forms_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FormResponse',
                'verbose_name_plural': 'FormResponses',
            },
        ),
        migrations.CreateModel(
            name='FormDocumentResponseCompanyPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('from_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.Company')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_document.FormDocumentResponse')),
                ('to_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.Company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormDocumentResponseUserPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms_responses_shared_to_other_users', to=settings.AUTH_USER_MODEL)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_document.FormDocumentResponse')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_responses_received_from_other_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormDocumentUserShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('form_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms_shared_to_other_users', to='form_document.FormDocument')),
                ('from_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms_received_from_other_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FormUserShare',
                'verbose_name_plural': 'FormUserShares',
            },
        ),
        migrations.AddField(
            model_name='formdocumentlink',
            name='form_response',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='form_document.FormDocumentResponse'),
        ),
        migrations.AddField(
            model_name='formdocumentlink',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='formdocumentusershare',
            unique_together=set([('form_document', 'to_user')]),
        ),
        migrations.AlterUniqueTogether(
            name='formdocumentcompanyshare',
            unique_together=set([('form_document', 'to_company')]),
        ),
    ]
