# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-27 15:19
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_auto_20160528_0119'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(default='Untitled Form', max_length=256)),
                ('slug', models.SlugField(help_text='Use for short URL sharing', null=True)),
                ('uploaded_document', models.FileField(help_text='The document uploaded used for populating after a form is completed', null=True, upload_to=b'')),
                ('form_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('owner', models.ForeignKey(help_text='The owner of this document', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormDocumentCompanyShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('share_to_all_members', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares_from_companies', to='accounts.Company')),
                ('form_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares_to_companies', to='form_document.FormDocument')),
            ],
        ),
        migrations.CreateModel(
            name='FormDocumentResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=30, null=True)),
                ('form_response_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('status', models.SmallIntegerField(choices=[(1, 'Unopen'), (5, 'Abandoned'), (2, 'Opened'), (3, 'Saved'), (4, 'Submitted')], default=1)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_document.FormDocument')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormDocumentSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('source', models.SmallIntegerField(choices=[(0, 'From form owner'), (1, 'From shared user'), (2, 'From shared company')], default=0)),
                ('company_share', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='form_document.FormDocumentCompanyShare')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormDocumentUserShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('send_response_to_owner_automatically', models.BooleanField(default=True, help_text='Send form response result to Form owner automatically')),
                ('form_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares_to_users', to='form_document.FormDocument')),
                ('shared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='form_document.FormDocumentCompanyShare')),
                ('shared_to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares_from_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='formdocumentsource',
            name='user_share',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='form_document.FormDocumentUserShare'),
        ),
        migrations.AddField(
            model_name='formdocumentresponse',
            name='form_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_document.FormDocumentSource'),
        ),
        migrations.AddField(
            model_name='formdocumentresponse',
            name='user',
            field=models.ForeignKey(help_text='The user who submitted the form, optional', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='formdocumentusershare',
            unique_together=set([('form_document', 'shared_to_user')]),
        ),
        migrations.AlterUniqueTogether(
            name='formdocumentcompanyshare',
            unique_together=set([('form_document', 'company')]),
        ),
    ]
