# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-18 04:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form_document', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdocumenttemplate',
            name='cached_form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='form_document.FixedFormDocument'),
        ),
    ]
