# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-27 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_document', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formdocument',
            options={'verbose_name': 'Form', 'verbose_name_plural': 'Forms'},
        ),
        migrations.AlterModelOptions(
            name='formdocumentcompanyshare',
            options={'verbose_name': 'FormCompanyShare', 'verbose_name_plural': 'FormCompanyShares'},
        ),
        migrations.AlterModelOptions(
            name='formdocumentresponse',
            options={'verbose_name': 'FormResponse', 'verbose_name_plural': 'FormResponses'},
        ),
        migrations.AlterModelOptions(
            name='formdocumentsource',
            options={'verbose_name': 'FormSource', 'verbose_name_plural': 'FormSources'},
        ),
        migrations.AlterModelOptions(
            name='formdocumentusershare',
            options={'verbose_name': 'FormUserShare', 'verbose_name_plural': 'FormUserShares'},
        ),
    ]
