# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-14 03:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_document', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formdocumentresponse',
            old_name='form_response_data',
            new_name='answers',
        ),
    ]
