# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-14 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_document', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdocumenttemplate',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Live')], default=0),
            preserve_default=False,
        ),
    ]
