# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-14 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_document', '0002_formdocumenttemplate_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdocumenttemplate',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Live')], default=0),
        ),
    ]
