# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-16 07:33
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_document', '0002_auto_20160614_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdocument',
            name='document_mapping',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), null=True, size=None),
        ),
        migrations.AddField(
            model_name='formdocument',
            name='form_config',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='formdocumentresponse',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Unopen'), (5, 'Abandoned'), (2, 'Opened'), (3, 'Saved'), (4, 'Submitted'), (6, 'Auto Saved')], default=1),
        ),
    ]
