# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-29 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_document', '0003_auto_20160528_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdocumentresponse',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formdocumentresponse',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
