# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-13 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_document', '0003_auto_20160920_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdocumenttemplate',
            name='number_of_pages',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
