# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-16 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form_document', '0003_auto_20160914_2118'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormDocumentAsset',
            new_name='FormDocumentTemplateDocumentPreview',
        ),
        migrations.AlterField(
            model_name='formdocumenttemplatedocumentpreview',
            name='form_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_assets', to='form_document.FormDocumentTemplate'),
        ),
    ]
