# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-16 08:48
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_document', '0003_auto_20160616_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdocument',
            name='form_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
