# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-13 07:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20161013_1720'),
        ('form_document', '0004_auto_20161013_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdocumentlink',
            name='receiver_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.Person'),
        ),
    ]
