# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-18 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import form_document.models
import storages.backends.gs


class Migration(migrations.Migration):

    dependencies = [
        ('form_document', '0005_auto_20160618_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdocumentassets',
            name='image',
            field=models.ImageField(storage=storages.backends.gs.GSBotoStorage(acl='private', bucket='emondo-documents', querystring_auth=True, querystring_expire=600), upload_to=form_document.models.document_path),
        ),
    ]
