# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-19 01:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_document', '0006_auto_20160618_2051'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormDocumentAssets',
            new_name='FormDocumentAsset',
        ),
    ]
