# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-17 11:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_document', '0004_formdocumenttemplate_number_of_pages'),
        ('form_document', '0006_auto_20161017_1214'),
    ]

    operations = [
    ]
