# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-20 00:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form_document', '0007_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdocumentresponseattachment',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='form_document.FormDocumentResponse'),
        ),
    ]
