# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-19 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import form_document.models
import storages.backends.gs


class Migration(migrations.Migration):

    dependencies = [
        ('form_document', '0007_auto_20160619_1100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formdocumentasset',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='formdocumentasset',
            name='order',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='formdocumentasset',
            name='form_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_assets', to='form_document.FormDocument'),
        ),
        migrations.AlterField(
            model_name='formdocumentasset',
            name='image',
            field=models.ImageField(storage=storages.backends.gs.GSBotoStorage(acl='private', bucket='emondo-documents', querystring_auth=True, querystring_expire=600), upload_to=form_document.models.original_document_path),
        ),
    ]
