# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-20 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_document', '0008_auto_20160619_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdocument',
            name='access_code',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
