# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-26 07:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form_document', '0009_auto_20161020_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdocumentlink',
            name='form_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='form_document.FormDocumentTemplate'),
        ),
    ]
