# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-24 02:13
from __future__ import unicode_literals

from django.db import migrations, models
import form_document.models
import storages.backends.gs


class Migration(migrations.Migration):

    dependencies = [
        ('form_document', '0010_auto_20160624_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdocument',
            name='uploaded_document',
            field=models.FileField(help_text='The document uploaded used for populating after a form is completed', max_length=255, null=True, storage=storages.backends.gs.GSBotoStorage(acl='private', bucket='emondo-documents', querystring_auth=True, querystring_expire=600), upload_to=form_document.models.document_path),
        ),
    ]
