# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-14 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_document', '0011_auto_20160624_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdocumentlink',
            name='sending_method',
            field=models.IntegerField(choices=[(0, 'Direct'), (1, 'Email'), (2, 'SMS')], default=0),
        ),
    ]
