# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-14 00:45
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import form_document.models


class Migration(migrations.Migration):

    dependencies = [
        ('form_document', '0011_formdocumenttemplate_archived_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdocumentresponse',
            name='populated_document',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=form_document.models.populated_pdf_file_path),
        ),
    ]
