# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-21 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_document', '0012_formdocumentlink_sending_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdocumentresponse',
            name='duration_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
