# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-14 01:01
from __future__ import unicode_literals

import core.core_storages
from django.db import migrations, models
import form_document.models


class Migration(migrations.Migration):

    dependencies = [
        ('form_document', '0012_formdocumentresponse_populated_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedformdocument',
            name='uploaded_document',
            field=models.FileField(help_text='The document uploaded used for populating after a form is completed', max_length=255, null=True, storage=core.core_storages.ProtectedDocumentStorage(), upload_to=form_document.models.form_document_cached_document_path),
        ),
        migrations.AlterField(
            model_name='formdocumentresponse',
            name='populated_document',
            field=models.FileField(null=True, storage=core.core_storages.ProtectedDocumentStorage(), upload_to=form_document.models.populated_pdf_file_path),
        ),
        migrations.AlterField(
            model_name='formdocumenttemplate',
            name='uploaded_document',
            field=models.FileField(help_text='The document uploaded used for populating after a form is completed', max_length=255, null=True, storage=core.core_storages.ProtectedDocumentStorage(), upload_to=form_document.models.form_document_template_uploaded_document_path),
        ),
        migrations.AlterField(
            model_name='formdocumenttemplatedocumentpreview',
            name='image',
            field=models.ImageField(height_field='cached_image_height', storage=core.core_storages.ProtectedDocumentStorage(), upload_to=form_document.models.form_document_template_uploaded_document_preview_path, width_field='cached_image_width'),
        ),
    ]
