# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-14 10:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_document', '0012_formdocumentresponse_assignee'),
        ('form_document', '0013_auto_20161114_1201'),
    ]

    operations = [
    ]
