# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-08 00:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_document', '0013_formdocumentresponse_duration_seconds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formdocument',
            name='site',
        ),
    ]
