# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-09 04:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_document', '0014_remove_formdocument_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formdocument',
            name='document_mapping',
        ),
    ]
