# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-14 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_document', '0014_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdocumenttemplate',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Live')], default=0),
        ),
    ]
