# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-09 04:07
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_document', '0015_remove_formdocument_document_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdocument',
            name='document_mapping',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
    ]
