# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-16 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_document', '0016_formdocument_document_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdocument',
            name='cached_sha1',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
