# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-18 03:21
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_document', '0017_formdocument_cached_sha1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdocument',
            name='document_mapping',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
