# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-06 06:06
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import form_document.models


class Migration(migrations.Migration):

    dependencies = [
        ('form_document', '0018_auto_20160818_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdocument',
            name='uploaded_document',
            field=models.FileField(help_text='The document uploaded used for populating after a form is completed', max_length=255, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=form_document.models.document_path),
        ),
        migrations.AlterField(
            model_name='formdocumentasset',
            name='image',
            field=models.ImageField(height_field='cached_image_height', storage=django.core.files.storage.FileSystemStorage(), upload_to=form_document.models.original_document_path, width_field='cached_image_width'),
        ),
    ]
