# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-18 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20161017_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='display_name',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
