# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-06 03:04
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('type', models.CharField(choices=[('m', 'Money based coupon'), ('p', 'Percentage discount')], max_length=1)),
                ('code', models.CharField(blank=True, help_text='Leaving this field empty will generate a random code.', max_length=30, unique=True, verbose_name='Code')),
                ('valid_until', models.DateTimeField(blank=True, help_text='Leave empty for coupons that never expire', null=True, verbose_name='Valid until')),
                ('single_user_reusable', models.BooleanField(default=False, verbose_name=django.db.models.fields.BooleanField)),
            ],
            options={
                'ordering': ['created'],
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('price_cents_monthly', models.IntegerField()),
                ('price_cents_yearly', models.IntegerField()),
                ('feature_flags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, size=None)),
                ('is_live', models.BooleanField(default=False)),
                ('min_required_user', models.SmallIntegerField(default=0)),
                ('max_required_user', models.SmallIntegerField(default=1)),
                ('trial_months_available', models.SmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='PlanSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('trial_days', models.SmallIntegerField(default=0)),
                ('price_cents', models.IntegerField()),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('active', models.BooleanField(default=False)),
                ('user_cancelled', models.BooleanField(default=False)),
                ('system_cancelled', models.BooleanField(default=False)),
                ('number_of_users', models.SmallIntegerField(default=1)),
                ('recurring_type', models.CharField(choices=[('0', 'No trial'), ('D', 'Day'), ('W', 'Week'), ('M', 'Month'), ('Y', 'Year')], max_length=1)),
                ('recurrence_period', models.PositiveIntegerField(blank=True, null=True)),
                ('next_payment_date', models.DateField(null=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.Coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date', 'user'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('reason', models.CharField(choices=[('S', 'Subscription charge'), ('P', 'Single product purchase')], default='', max_length=1)),
                ('description', models.CharField(blank=True, max_length=128)),
                ('amount_cents', models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='Amount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-amount_cents'],
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.AddField(
            model_name='coupon',
            name='target_plans',
            field=models.ManyToManyField(help_text='Leaving empty will make this coupon valid for all plans', null=True, to='billing.Plan'),
        ),
    ]
