# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-20 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='max_required_user',
            field=models.SmallIntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='trial_months_available',
            field=models.SmallIntegerField(default=1, null=True),
        ),
    ]
