# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-01 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_auto_20160901_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plansubscription',
            name='plan_pricing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.PlanPricing'),
        ),
    ]
