# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-01 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_auto_20160901_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planpricing',
            name='price_cents',
        ),
        migrations.AddField(
            model_name='pricing',
            name='price_cents',
            field=models.IntegerField(default=1000),
        ),
    ]
