# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-02 05:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_auto_20160901_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecard',
            name='fingerprint',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='stripecustomer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
