# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-03 00:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_auto_20160902_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plansubscription',
            name='coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.Coupon'),
        ),
    ]
