# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-03 00:33
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_auto_20160903_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plansubscription',
            name='amount_cents',
        ),
        migrations.AlterField(
            model_name='plan',
            name='feature_flags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, default=[], size=None),
        ),
    ]
