# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-04 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_auto_20160903_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='recurring_type',
            field=models.CharField(choices=[('D', 'daily'), ('W', 'weekly'), ('M', 'monthly'), ('Y', 'annually')], default='M', max_length=1),
        ),
    ]
