# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-07 10:45
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=64)),
                ('state', models.CharField(blank=True, max_length=64)),
                ('card_number', models.CharField(blank=True, max_length=64)),
                ('expiry_date', models.DateField(null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32)),
                ('expiry_date', models.DateField()),
                ('place_of_birth', models.CharField(max_length=128)),
                ('mrz1', models.CharField(blank=True, max_length=64)),
                ('mrz2', models.CharField(blank=True, max_length=64)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Person')),
            ],
        ),
        migrations.CreateModel(
            name='PersonVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Pass'), (2, 'Rejected'), (0, 'Unknown')])),
                ('source', models.PositiveSmallIntegerField(choices=[(1, b'DVSDriverLicense'), (0, b'DVSDriverLicense'), (2, b'DVSDriverLicense'), (3, b'Australian Electoral Roll'), (4, b'Australian Credit Agency'), (5, b'Manual File Upload')])),
                ('raw_response', django.contrib.postgres.fields.jsonb.JSONField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonVerificationAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(), upload_to='verification-attachments')),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity_verification.PersonVerification')),
            ],
        ),
    ]
