# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-07 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity_verification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personverification',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pass'), (2, 'Rejected'), (0, 'Unknown')], default=0),
        ),
    ]
