# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-07 15:13
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity_verification', '0002_auto_20160908_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personverification',
            name='raw_response',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
    ]
