# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-08 03:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('identity_verification', '0004_auto_20160908_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personverificationattachment',
            name='verification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='identity_verification.PersonVerification'),
        ),
    ]
