# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-08 03:51
from __future__ import unicode_literals

import datetime
import django.core.files.storage
from django.db import migrations, models
from django.utils.timezone import utc
import identity_verification.models


class Migration(migrations.Migration):

    dependencies = [
        ('identity_verification', '0005_auto_20160908_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='personverificationattachment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 9, 8, 3, 51, 1, 805249, tzinfo=utc), verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personverificationattachment',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 9, 8, 3, 51, 8, 197570, tzinfo=utc), verbose_name='modified'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personverificationattachment',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(), upload_to=identity_verification.models.year_month_day_path),
        ),
    ]
