# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-10 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity_verification', '0007_medicarecard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicarecard',
            name='expiry_date',
        ),
        migrations.AddField(
            model_name='medicarecard',
            name='expiry_date_month',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='medicarecard',
            name='expiry_date_year',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
