# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-14 01:01
from __future__ import unicode_literals

import core.core_storages
from django.db import migrations, models
import identity_verification.models


class Migration(migrations.Migration):

    dependencies = [
        ('identity_verification', '0008_auto_20160910_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personverificationattachment',
            name='file',
            field=models.FileField(storage=core.core_storages.ProtectedDocumentStorage(), upload_to=identity_verification.models.year_month_day_path),
        ),
    ]
