# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-11 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import feincms.contrib.richtext
import feincms.extensions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=False, verbose_name='published')),
                ('title', models.CharField(help_text='This is used for the generated navigation too.', max_length=100, verbose_name='title')),
                ('published_on', models.DateTimeField(help_text='The date on which the blog entry is visible.', null=True)),
                ('excerpt', models.TextField(blank=True, help_text='Add a brief excerpt summarizing the content of this page.', null=True)),
                ('slug', models.SlugField(max_length=100)),
                ('template_key', models.CharField(choices=[(b'blog/article.html', 'Blog')], default=b'blog/article.html', max_length=255, verbose_name='template')),
            ],
            options={
                'ordering': ['-published_on'],
                'get_latest_by': 'published_on',
                'verbose_name': 'blog entry',
                'verbose_name_plural': 'blog entries',
            },
            bases=(models.Model, feincms.extensions.ExtensionsMixin),
        ),
        migrations.CreateModel(
            name='RawContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='content')),
                ('region', models.CharField(max_length=255)),
                ('ordering', models.IntegerField(default=0, verbose_name='ordering')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rawcontent_set', to='blog.BlogEntry')),
            ],
            options={
                'ordering': ['ordering'],
                'abstract': False,
                'verbose_name_plural': 'raw contents',
                'db_table': 'blog_blogentry_rawcontent',
                'verbose_name': 'raw content',
                'permissions': [],
            },
        ),
        migrations.CreateModel(
            name='RichTextContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', feincms.contrib.richtext.RichTextField(blank=True, verbose_name='text')),
                ('region', models.CharField(max_length=255)),
                ('ordering', models.IntegerField(default=0, verbose_name='ordering')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='richtextcontent_set', to='blog.BlogEntry')),
            ],
            options={
                'ordering': ['ordering'],
                'abstract': False,
                'verbose_name_plural': 'rich texts',
                'db_table': 'blog_blogentry_richtextcontent',
                'verbose_name': 'rich text',
                'permissions': [],
            },
        ),
    ]
