# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-11 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, upload_to='imagecontent', verbose_name='image')),
                ('alt_text', models.CharField(blank=True, help_text='Description of image', max_length=255, verbose_name='alternate text')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='caption')),
                ('region', models.CharField(max_length=255)),
                ('ordering', models.IntegerField(default=0, verbose_name='ordering')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagecontent_set', to='blog.BlogEntry')),
            ],
            options={
                'ordering': ['ordering'],
                'abstract': False,
                'verbose_name_plural': 'images',
                'db_table': 'blog_blogentry_imagecontent',
                'verbose_name': 'image',
                'permissions': [],
            },
        ),
    ]
