# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-11 21:45
from __future__ import unicode_literals

import cms.blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_imagecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogentry',
            name='hero_image',
            field=models.ImageField(null=True, upload_to=cms.blog.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='blogentry',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='imagecontent',
            name='image',
            field=models.ImageField(max_length=255, upload_to='cms/imagecontent', verbose_name='image'),
        ),
    ]
