# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-12 02:43
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20160512_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
