# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-13 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20160512_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
