# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 04:35
from __future__ import unicode_literals

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_pre_launch_signup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default='AU', max_length=2),
        ),
    ]
