# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20160328_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signup_form_source',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='user',
            name='signup_tag_index',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
