# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-27 15:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20160512_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('active', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='accounts.Company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('add_member', models.BooleanField(default=False)),
                ('edit_member', models.BooleanField(default=False)),
                ('delete_member', models.BooleanField(default=False)),
                ('add_billing', models.BooleanField(default=False)),
                ('edit_billing', models.BooleanField(default=False)),
                ('delete_billing', models.BooleanField(default=False)),
                ('manage_plan', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='companymember',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.CompanyPermission'),
        ),
        migrations.AddField(
            model_name='companymember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
