# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-14 06:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20160528_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymember',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='accounts.Company'),
        ),
        migrations.AlterField(
            model_name='companymember',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
