# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-11 07:38
from __future__ import unicode_literals

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20160714_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone1',
            field=timezone_field.fields.TimeZoneField(default='Australia/Sydney'),
        ),
    ]
