# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-04 00:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_timezone1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='timezone1',
            new_name='timezone',
        ),
    ]
