# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-02 23:28
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AFSAuthorisedRepresentative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=256)),
                ('license_no', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AFSLicenseeEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=256)),
                ('license_no', models.IntegerField()),
                ('abn', models.IntegerField()),
                ('commenced_date', models.DateField(null=True)),
                ('service_address', models.CharField(max_length=512)),
                ('status', models.CharField(max_length=32)),
                ('principle_business_address', models.CharField(max_length=512)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataSourceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Admin Visible'), (2, 'Live')])),
                ('source_name', models.CharField(max_length=64)),
                ('columns', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=32), size=None)),
                ('model_name', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='afsauthorisedrepresentative',
            name='licensed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_explorer.AFSLicenseeEntry'),
        ),
    ]
