# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-03 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_explorer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='afsauthorisedrepresentative',
            options={'verbose_name': 'Australian Financial Services Authorised Representative', 'verbose_name_plural': 'Australian Financial Services Authorised Representatives'},
        ),
        migrations.AlterModelOptions(
            name='afslicenseeentry',
            options={'verbose_name': 'Australian Financial Services Licensee', 'verbose_name_plural': 'Australian Financial Services Licensee'},
        ),
        migrations.AddField(
            model_name='afslicenseeentry',
            name='acn',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='afslicenseeentry',
            name='abn',
            field=models.IntegerField(null=True),
        ),
    ]
