# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-09 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_explorer', '0007_justiceofpeace'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='justiceofpeace',
            options={'verbose_name': 'Justice Of Peace', 'verbose_name_plural': 'Justice Of Peace'},
        ),
        migrations.AddField(
            model_name='justiceofpeace',
            name='suburb',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Suburb'),
        ),
        migrations.AlterField(
            model_name='justiceofpeace',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='justiceofpeace',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='justiceofpeace',
            name='jp_number',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='justiceofpeace',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='justiceofpeace',
            name='mobile_number',
            field=models.CharField(blank=True, default='', max_length=24, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='justiceofpeace',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=24, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='justiceofpeace',
            name='phone2',
            field=models.CharField(blank=True, default='', help_text='After hour', max_length=24, verbose_name='Contact Number2'),
        ),
        migrations.AlterField(
            model_name='justiceofpeace',
            name='state',
            field=models.CharField(blank=True, default='', max_length=24, verbose_name='State'),
        ),
    ]
