# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-10 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_explorer', '0008_auto_20160509_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='justiceofpeace',
            name='mobile_number',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='justiceofpeace',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='justiceofpeace',
            name='phone2',
            field=models.CharField(blank=True, default='', help_text='After hour', max_length=128, verbose_name='Contact Number2'),
        ),
        migrations.AlterField(
            model_name='justiceofpeace',
            name='state',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='State'),
        ),
    ]
