# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-14 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_explorer', '0011_auto_20160914_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasourcemodel',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Live')], default=0),
        ),
    ]
