# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-10 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMSNotificationTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('remote_id', models.CharField(max_length=128, null=True)),
                ('user_response', models.CharField(max_length=256, null=True)),
                ('message', models.CharField(max_length=512)),
                ('dest_number', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
