# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-11 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsnotificationtransaction',
            name='status',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
